blank_issues_enabled: false
contact_links:
  - name: Contribution guide
    url: https://github.com/kvndrsslr/sketchybar-app-font/blob/main/CONTRIBUTING.md
    about: Learn how to add an icon yourself — it's easier than you think!
